//---------------------------------------------------------------------------------------------------------
// Program Declarations & I/O Variables
//---------------------------------------------------------------------------------------------------------
#pragma kernel CSMain

RWTexture3D<float4> Tex3D;

float Tex3DRes;
float Scale = 1;


// #include "Libraries/ExampleNoise.hlsl"
#include "Libraries/SimplexNoise3D.hlsl"

//---------------------------------------------------------------------------------------------------------
// Generator Functions
//---------------------------------------------------------------------------------------------------------

//Needs to be passed in to the C# script via the inspector
[numthreads(8,8,8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	float3 xyz = ((float3)id.xyz)/Scale / Tex3DRes;
	Tex3D[id.xyz] = float4(snoise(xyz).xxxx);
}
